### ISSUE TITLE
Expose Schnorrkel's VRF capabilities

### ISSUE THREAD

**Issue by stiiifff** [polkadot-js/wasm#168]
Expose Schnorrkel's VRF capabilities to WASM / JS environments.
Having a verifiable source of randomness will will enable interesting use cases for wallet / dapp builders.
Methods to be exposed: vrf_sign, vrf_sign_extra, vrf_verify, vrf_verify_extra.

**Comment by stiiifff** [comment]
@jacogr These should ultimately be exposed in a standardized way to app / wallet builders, through the API lib (Signer, Provider etc), and probably the browser extension as well. I'm trying to figure out the impacted libs, and the issues to be created on the various repos ... but not super familiar with the codebases, so I'm looking for guidance on this.

**Comment by jacogr** [comment]
Once exposed here the rest will just follow - as part of the update of wasm the interfaces are added. 

If specific actions are needed at that point issues can be logged elsewhere. As of now issues in other repos are just adding noise since there is nothing that anybody can do in those repos.

Bear in mind that unless there is a clear explicit usecase, it is unlikely to be added. The WASM doesn't expose everything the underlying libs provide. (If it did, the bundle size and number of testcases provided here would explode)

**Comment by stiiifff** [comment]
Thanks. To give your more context, I have a specific use case (for a wallet provider) which is to be able to use the **vrf_sign_extra** method to get a deterministic signature (with an arbitrary payload).
This deterministic signature can then be used as deterministic entropy by app / wallet builders. This is a useful thing to have as SR25519 signatures are non-deterministic, and some app / wallet providers rely on the fact that ECDSA signatures are deterministic in Ethereum. I've discussed with Jeff (W3F), and the suggested approach to replicate that behavior is to leverage VRF with an arbitrary payload.
Ideally, a wallet provider should be able to request the VRF signature from an account (whether from the local keyring, or injected / external).
