### ISSUE TITLE
How to use JavaScript using wasm in Java?

### ISSUE THREAD

**Issue by paperfrog1228** [polkadot-js/wasm#293]
Hello everyone!
I'm java developer working on coin exchange.
We found out that there was no Java related to Polkadot, and we are trying to actively use polkadot-js.
**But we will use it in Java.**

The method I tried is as follows.
1. use [GraalVm](https://github.com/oracle/graal)(It's a simple library that binds JavaScript)
2. use webpack (use your modules to use in one js file)
3. and run!

But I'm fighting the error below :(
![image](https://user-images.githubusercontent.com/11247319/155698510-2bba4d3b-7e0a-44de-9291-3189c48e1eb7.png)

Is the method I tried technically possible?

The functions that our exchange needs are as follows.
- generating signle/multi-signed addresses
- broadcasting transactions
- parsing block network information (blocks, extrinsics, call, events, etc, ...)

All the crypto-related functions of polkadot-js are related to wasm.
So I think we should use wasm unconditionally.

question
- Is there a way to solve the above error?
- Is the method I tried technically possible??

**Comment by jacogr** [comment]
Honestly have no idea, have not used Java since 1998 and never heard of GraalVm, so cannot be of help with integration. Google yields some results (and that would be your best support forum), see https://www.graalvm.org/22.0/reference-manual/wasm/

WASM is moistly required, areas such as sr25519 is only available in WASM. (For the rest the `@polkadot/util-crypto` does provide JS fallbacks when WASM is not available)

I know there were teams that received grants from the W3F to provide a Java SDK, but AFAIK those have not been worked on in > 18 months now.

**Comment by paperfrog1228** [comment]
Thank you! :)
These functions are definitely using WASM, right?

- generating signle/multi-signed addresses
- broadcasting transactions
- parsing block network information (blocks, extrinsics, call, events, etc, ...)

**Comment by jacogr** [comment]
Only the first, assuming you are using sr25519 accounts.

**Comment by jacogr** [comment]
One thing I didn't mention. The npm package includes both WASM and ASM.js versions, the former is the default, the latter is used in e.g. React-Native. So if you are using Webpack along the way, you can actually alias the WASM to the ASM.js interfaces, which is just JS.

See https://polkadot.js.org/docs/util-crypto/FAQ#im-using-a-web-bundler-and-have-no-need-for-wasm-or-sr25519

This is how RN is configured, it points the entry point to `data.js`, so that part (quite large) gets used. 

https://github.com/polkadot-js/wasm/blob/master/packages/wasm-crypto-asmjs/package.json#L23

**Comment by paperfrog1228** [comment]
Thank you! @jacogr  I'm late because of the weekend. 
Asmjs! I think this is the answer I'm looking for.
I think we're almost there.

Can I know how to link this data.js in ordinary js other than react native?

I'm also looking for it, but I don't know because I'm weak at js.

Your answer is very helpful.

**Comment by jacogr** [comment]
To link, you would need something like this in your webpack alias (this means the default will always map to the data path) -

```
'@polkadot/wasm-crypto-asmjs': require.resolve('@polkadot/wasm-crypto-asmjs/data')
```

**Comment by paperfrog1228** [comment]
I'll say it again. @jacogr 
Thank you so much. I'll list Polkadot on our exchange.
I think I can use polkadot-js freely after seeing someone like you.

I'm not good at English, so I don't know if it was delivered well,
I'm so very grateful to you. Have a good day!
