### ISSUE TITLE
@polkadot/api doesn't get initialised unless the asmInit is passed explicitly

### ISSUE THREAD

**Issue by ishrak-imam** [polkadot-js/wasm#339]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@polkadot/wasm-crypto@6.0.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@polkadot/wasm-crypto/cjs/init.js b/node_modules/@polkadot/wasm-crypto/cjs/init.js
index cbdb8d5..a5cf3b3 100644
--- a/node_modules/@polkadot/wasm-crypto/cjs/init.js
+++ b/node_modules/@polkadot/wasm-crypto/cjs/init.js
@@ -10,6 +10,7 @@ exports.setWasmPromiseFn = setWasmPromiseFn;
 var _util = require("@polkadot/util");
 
 var _wasmCryptoWasm = require("@polkadot/wasm-crypto-wasm");
+var _asmCryptoWasm = require("@polkadot/wasm-crypto-asmjs");
 
 var _bridge = require("./bridge");
 
@@ -50,5 +51,5 @@ function setWasmPromiseFn(fn) {
 }
 
 function initWasm() {
-  return setWasmPromise(_wasmCryptoWasm.wasmBytes, null);
+  return setWasmPromise(_wasmCryptoWasm.wasmBytes, _asmCryptoWasm.asmJsInit);
 }
\ No newline at end of file
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Using the package in react-native where WASM is not available and `waitReady` or `cryptoWaitReady` or `import '@polkadot/wasm-crypto/initWasmAsm'` at the start of the application none of this workarounds solve the problem.

**Comment by jacogr** [comment]
The issue is that asmJs cannot be enabled by default. It really bloats the bundles completely since it is massive. So the idea is that in other environments where you need asJs fallbacks is that you should use the `initWasmAsm` or `initOnlyAsm` directives, i.e. in the [CHANGELOG for 5.1.1](https://github.com/polkadot-js/wasm/releases/tag/v5.0.1)

Well, that is the idea, it _seems_ to be creating some problems on RN as it stands, which is currently an open issue in the common repo.

The thinking currently is to re-introduce a RN import override, i.e. for RN specifically to follow a different path an enable both instead of trying to force the user themselves to add the entry-points. (Which then seems to run out of order in certain cases - at leats on RN, in the tests here it does all fall in place, as expected)

**Comment by jacogr** [comment]
Follow-up, in [this PR](https://github.com/polkadot-js/wasm/pull/340) RN gets a default import alias to point to the asm stuff.

**Comment by jacogr** [comment]
Going to close this one in favor of https://github.com/polkadot-js/common/issues/1456 - judging by [this comment](https://github.com/polkadot-js/common/issues/1456#issuecomment-1123112167) the linked PR did the right thing here.
