### ISSUE TITLE
Provide build instructions to verify bytecode

### ISSUE THREAD

**Issue by jonathunne** [polkadot-js/wasm#423]
Hey,

This code is compiled and built for use in a few browser extensions, and the Chrome store policies these extensions have to adhere to often [restrict obfuscated code](https://developer.chrome.com/docs/webstore/troubleshooting/#obfuscation).

With this, it would be useful to include instructions in this repo, with some Dockerfile or similar, on how to generate the bytes that are uploaded to the npm package at [npmjs.com](https://www.npmjs.com/package/@polkadot/wasm-crypto), so the reviewers can verify the source.

A good example of this in practice is the uBlock Origin extension, which also contains compiled WASM: https://github.com/gorhill/uBlock/blob/master/src/js/wasm/README.md)

**Comment by jacogr** [comment]
CI simply executes “yarn build” and publishes that tag to npm. 

The specific steps are here - https://github.com/polkadot-js/wasm/blob/master/scripts/build-wasm.sh

**Comment by jonathunne** [comment]
Any details on the build environment? It seems that [deterministic outputs aren't a guarantee with rust](https://github.com/rust-lang/rust/issues/34902), and so I haven't been able to match the bytes in the npm package by running `yarn build`.

**Comment by jacogr** [comment]
It is non-deterministic since it is also known to add paths. However these are part of stacks, which we try to strip completely - have no looked at the raw release output in ages so there may still be some. The Rust version and wasm-bindgen versions do matter, different versions will do different things.

Rust version is set at 

https://github.com/polkadot-js/wasm/blob/8db05486c0cacb08b4a9cc37864b3dc6dcfd2c1f/scripts/rust-version.sh#L6

Which is then used at 

https://github.com/polkadot-js/wasm/blob/master/scripts/install-build-deps.sh

(Rust/bindgen version do change at points, but it costs a lot of verification before such a change is made in terms of tests and then actual output sizes as well)
